### ISSUE TITLE
Share HarmonyOS Sans Config

### ISSUE THREAD

**Issue by lcandy2** [chawyehsu/mactype-profile#2]
Would you mind share your config using HarmonyOS Sans?
I changed the font of your ini, but the font size is too heavy.

**Comment by chawyehsu** [comment]
There is only font substitutes difference between the two configurations, you just change all `XHei WP *` font in the `[FontSubstitutes]` part to `HarmonyOS Sans SC`.

I don't quite understand what you mean by `too heavy`, could you please take some screenshots for it?
